/**
 * This class file was automatically generated by jASN1 v1.11.0 (http://www.beanit.com)
 */

package pkix1explicit88;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;
import com.beanit.jasn1.ber.types.string.*;


public class AttCertVersion extends BerInteger {

	private static final long serialVersionUID = 1L;

	public AttCertVersion() {
	}

	public AttCertVersion(byte[] code) {
		super(code);
	}

	public AttCertVersion(BigInteger value) {
		super(value);
	}

	public AttCertVersion(long value) {
		super(value);
	}

}
