/**
 * This class file was automatically generated by jASN1 v1.11.0 (http://www.beanit.com)
 */

package pkix1explicit88;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;
import com.beanit.jasn1.ber.types.string.*;


public class AttributeCertificateInfo implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private AttCertVersion version = null;
	private Holder holder = null;
	private AttCertIssuer issuer = null;
	private AlgorithmIdentifier signature = null;
	private CertificateSerialNumber serialNumber = null;
	private AttCertValidityPeriod attrCertValidityPeriod = null;
	private NameAttributes attributes = null;
	private Extensions extensions = null;
	
	public AttributeCertificateInfo() {
	}

	public AttributeCertificateInfo(byte[] code) {
		this.code = code;
	}

	public void setVersion(AttCertVersion version) {
		this.version = version;
	}

	public AttCertVersion getVersion() {
		return version;
	}

	public void setHolder(Holder holder) {
		this.holder = holder;
	}

	public Holder getHolder() {
		return holder;
	}

	public void setIssuer(AttCertIssuer issuer) {
		this.issuer = issuer;
	}

	public AttCertIssuer getIssuer() {
		return issuer;
	}

	public void setSignature(AlgorithmIdentifier signature) {
		this.signature = signature;
	}

	public AlgorithmIdentifier getSignature() {
		return signature;
	}

	public void setSerialNumber(CertificateSerialNumber serialNumber) {
		this.serialNumber = serialNumber;
	}

	public CertificateSerialNumber getSerialNumber() {
		return serialNumber;
	}

	public void setAttrCertValidityPeriod(AttCertValidityPeriod attrCertValidityPeriod) {
		this.attrCertValidityPeriod = attrCertValidityPeriod;
	}

	public AttCertValidityPeriod getAttrCertValidityPeriod() {
		return attrCertValidityPeriod;
	}

	public void setAttributes(NameAttributes attributes) {
		this.attributes = attributes;
	}

	public NameAttributes getAttributes() {
		return attributes;
	}

	public void setExtensions(Extensions extensions) {
		this.extensions = extensions;
	}

	public Extensions getExtensions() {
		return extensions;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (extensions != null) {
			codeLength += extensions.encode(reverseOS, true);
		}
		
		codeLength += attributes.encode(reverseOS, true);
		
		codeLength += attrCertValidityPeriod.encode(reverseOS, true);
		
		codeLength += serialNumber.encode(reverseOS, true);
		
		codeLength += signature.encode(reverseOS, true);
		
		codeLength += issuer.encode(reverseOS);
		
		codeLength += holder.encode(reverseOS, true);
		
		codeLength += version.encode(reverseOS, true);
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		if (berTag.equals(AttCertVersion.tag)) {
			version = new AttCertVersion();
			subCodeLength += version.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(Holder.tag)) {
			holder = new Holder();
			subCodeLength += holder.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		issuer = new AttCertIssuer();
		subCodeLength += issuer.decode(is, berTag);
		subCodeLength += berTag.decode(is);
		
		if (berTag.equals(AlgorithmIdentifier.tag)) {
			signature = new AlgorithmIdentifier();
			subCodeLength += signature.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(CertificateSerialNumber.tag)) {
			serialNumber = new CertificateSerialNumber();
			subCodeLength += serialNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(AttCertValidityPeriod.tag)) {
			attrCertValidityPeriod = new AttCertValidityPeriod();
			subCodeLength += attrCertValidityPeriod.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(NameAttributes.tag)) {
			attributes = new NameAttributes();
			subCodeLength += attributes.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(Extensions.tag)) {
			extensions = new Extensions();
			subCodeLength += extensions.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (version != null) {
			sb.append("version: ").append(version);
		}
		else {
			sb.append("version: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (holder != null) {
			sb.append("holder: ");
			holder.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("holder: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (issuer != null) {
			sb.append("issuer: ");
			issuer.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("issuer: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (signature != null) {
			sb.append("signature: ");
			signature.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("signature: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (serialNumber != null) {
			sb.append("serialNumber: ").append(serialNumber);
		}
		else {
			sb.append("serialNumber: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (attrCertValidityPeriod != null) {
			sb.append("attrCertValidityPeriod: ");
			attrCertValidityPeriod.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("attrCertValidityPeriod: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (attributes != null) {
			sb.append("attributes: ");
			attributes.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("attributes: <empty-required-field>");
		}
		
		if (extensions != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("extensions: ");
			extensions.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

